from typing import Any

from . import __version__

_GOVERNED_ADAPTERS: tuple[dict[str, Any], ...] = (
    {
        "id": "local_status",
        "title": "Local status adapter",
        "kind": "internal_adapter",
        "domain": "system_status",
        "channels": ["gateway", "workbench"],
        "autonomy": "governed_local_read_only",
        "entrypoints": ["/v1/gateway/adapter-dispatcher"],
        "requested_capabilities": ["local_status.status", "local_status.echo"],
        "granted_capabilities": ["local_status.status", "local_status.echo"],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "local_handler_registered": True,
        "network_access_enabled": False,
        "credentialed_access_enabled": False,
        "filesystem_read_enabled": False,
        "filesystem_write_enabled": False,
        "shell_execution_enabled": False,
        "external_side_effects_enabled": False,
        "human_approval_required_for": [],
        "status": "local_handler",
        "purpose": "Execute a minimal in-process local status response without shell, network, credentials, or filesystem access.",
    },
    {
        "id": "mcp",
        "title": "MCP broker foundation",
        "kind": "protocol_adapter",
        "domain": "tools",
        "channels": ["gateway", "workbench"],
        "autonomy": "policy_checked_read_only",
        "entrypoints": [
            "/v1/harness/mcp/status",
            "/v1/harness/mcp/tools",
            "/v1/harness/mcp/policy-check",
        ],
        "requested_capabilities": ["mcp.status", "mcp.list_tools", "mcp.policy_check"],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "human_approval_required_for": ["mcp.call_tool", "credentialed_tool", "filesystem_write", "network_side_effect"],
        "status": "foundation_only",
        "purpose": "Inspect MCP broker metadata and classify tool calls without executing tools.",
    },
    {
        "id": "browser",
        "title": "Browser automation contract",
        "kind": "capability_adapter",
        "domain": "web",
        "channels": ["gateway", "workbench"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "browser.plan",
            "browser.navigate_public",
            "browser.extract_public",
            "browser.screenshot_public",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "network_access_enabled": False,
        "credentialed_access_enabled": False,
        "human_approval_required_for": [
            "browser.navigate_public",
            "browser.authenticated_session",
            "browser.form_submit",
            "browser.click_external",
            "browser.download_file",
            "network_side_effect",
        ],
        "status": "contract_only",
        "purpose": "Declare browser automation boundaries before exposing any browser execution surface.",
    },
    {
        "id": "n8n",
        "title": "n8n automation contract",
        "kind": "automation_adapter",
        "domain": "automation",
        "channels": ["gateway", "workbench"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "n8n.plan_workflow",
            "n8n.inspect_workflow",
            "n8n.validate_workflow",
            "n8n.dry_run_workflow",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "workflow_execution_enabled": False,
        "credentialed_access_enabled": False,
        "external_side_effects_enabled": False,
        "human_approval_required_for": [
            "n8n.create_workflow",
            "n8n.update_workflow",
            "n8n.activate_workflow",
            "n8n.execute_workflow",
            "n8n.credentialed_node",
            "n8n.webhook_public",
            "network_side_effect",
        ],
        "status": "contract_only",
        "purpose": "Declare n8n automation boundaries before exposing workflow creation or execution.",
    },
    {
        "id": "voice",
        "title": "Voice MVP contract",
        "kind": "interface_adapter",
        "domain": "voice",
        "channels": ["gateway", "workbench", "mobile"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "voice.plan",
            "voice.transcribe_local",
            "voice.synthesize_local",
            "voice.route_command",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "audio_capture_enabled": False,
        "wake_word_enabled": False,
        "credentialed_access_enabled": False,
        "external_side_effects_enabled": False,
        "human_approval_required_for": [
            "voice.capture_microphone",
            "voice.wake_word_listener",
            "voice.send_transcript_external",
            "voice.invoke_action",
            "voice.send_message",
            "voice.modify_calendar",
            "network_side_effect",
        ],
        "status": "contract_only",
        "purpose": "Declare voice interface boundaries before exposing microphone capture, wake-word listening, STT/TTS, or command execution.",
    },
    {
        "id": "model_lab",
        "title": "Model lab contract",
        "kind": "evaluation_adapter",
        "domain": "models",
        "channels": ["gateway", "workbench"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "model_lab.plan_eval",
            "model_lab.inspect_runtime",
            "model_lab.read_model_metadata",
            "model_lab.dry_run_eval_plan",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "model_download_enabled": False,
        "benchmark_execution_enabled": False,
        "runtime_mutation_enabled": False,
        "network_access_enabled": False,
        "credentialed_access_enabled": False,
        "human_approval_required_for": [
            "model_lab.download_model",
            "model_lab.start_runtime",
            "model_lab.run_benchmark",
            "model_lab.change_runtime_config",
            "model_lab.access_gpu",
            "model_lab.upload_results",
            "filesystem_write",
            "network_side_effect",
        ],
        "status": "contract_only",
        "purpose": "Declare local model lab boundaries before downloads, benchmarks, runtime changes, or model execution.",
    },
    {
        "id": "social_career",
        "title": "Social and career automation contract",
        "kind": "automation_adapter",
        "domain": "career_social",
        "channels": ["gateway", "workbench"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "social_career.plan_content",
            "social_career.draft_post",
            "social_career.inspect_pipeline",
            "social_career.prepare_application_packet",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "publication_enabled": False,
        "message_sending_enabled": False,
        "application_submission_enabled": False,
        "form_submission_enabled": False,
        "credentialed_access_enabled": False,
        "external_side_effects_enabled": False,
        "human_approval_required_for": [
            "social_career.publish_post",
            "social_career.send_message",
            "social_career.submit_application",
            "social_career.submit_form",
            "social_career.use_credentialed_account",
            "network_side_effect",
        ],
        "status": "contract_only",
        "purpose": "Declare social and career automation boundaries before publishing, messaging, forms, or applications.",
    },
    {
        "id": "document_media",
        "title": "Document and media agent contract",
        "kind": "content_adapter",
        "domain": "documents_media",
        "channels": ["gateway", "workbench"],
        "autonomy": "contract_only",
        "entrypoints": [],
        "requested_capabilities": [
            "document.plan_ingestion",
            "document.extract_text_local",
            "document.summarize_local",
            "media.inspect_metadata_local",
        ],
        "granted_capabilities": [],
        "executes_tools": False,
        "grants_permissions": False,
        "requires_policy_check": True,
        "document_ingestion_enabled": False,
        "ocr_enabled": False,
        "transcription_enabled": False,
        "external_upload_enabled": False,
        "destructive_processing_enabled": False,
        "filesystem_scope": "repo_or_explicit_sandbox_only",
        "human_approval_required_for": [
            "document.read_external_path",
            "document.ocr",
            "media.transcribe",
            "media.upload_external",
            "filesystem_write",
            "destructive_processing",
        ],
        "status": "contract_only",
        "purpose": "Declare document and media processing boundaries before exposing ingestion, OCR, transcription, upload, or destructive processing.",
    },
)


def governed_adapters() -> list[dict[str, Any]]:
    return [dict(adapter) for adapter in _GOVERNED_ADAPTERS]


def collect_adapter_registry(*, adapter_id: str | None = None) -> dict[str, Any]:
    adapters = governed_adapters()
    if adapter_id:
        adapters = [adapter for adapter in adapters if adapter["id"] == adapter_id]
    return {
        "product": "lai-gateway",
        "version": __version__,
        "operation": "adapter-registry",
        "overall": "ready" if adapters else "missing",
        "count": len(adapters),
        "adapters": adapters,
        "starts_server": False,
        "modifies_files": False,
        "executes_tools": any(adapter.get("executes_tools") for adapter in adapters),
        "security": {
            "prints_tokens": False,
            "grants_permissions": any(adapter.get("grants_permissions") for adapter in adapters),
            "channels_elevate_permissions": False,
            "skills_elevate_permissions": False,
            "tool_execution_enabled": any(adapter.get("executes_tools") for adapter in adapters),
        },
    }


def render_adapter_registry(payload: dict[str, Any]) -> str:
    lines = [
        f"lai-gateway adapter-registry: {payload['overall']}",
        f"version: {payload['version']}",
        f"count: {payload['count']}",
        "grants_permissions: false",
        "tool_execution_enabled: false",
    ]
    for adapter in payload.get("adapters", []):
        requested = ", ".join(adapter.get("requested_capabilities", [])) or "none"
        granted = ", ".join(adapter.get("granted_capabilities", [])) or "none"
        lines.append(
            f"- {adapter['id']}: kind={adapter['kind']} autonomy={adapter['autonomy']} requested={requested} granted={granted} executes_tools={adapter.get('executes_tools', False)}"
        )
    return "\n".join(lines)
