from __future__ import annotations

CONTRACT = {
    "schema_version": 1,
    "product": "lai harness",
    "version": "0.4.7",
    "repository": "/tmp/lai-local-agent",
    "transport": {
        "server": "lai serve",
        "bind_policy": "loopback-only",
        "default_bind": "127.0.0.1",
        "default_port": 8765,
        "auth": "Authorization: Bearer <control-api-token>",
        "content_type": "application/json; charset=utf-8",
        "cache_control": "no-store",
    },
    "capabilities": {
        "model_execution": True,
        "policy_classification": True,
        "persistent_sessions": True,
        "async_read_only_runs": True,
        "async_work_runs": True,
        "sandbox_workspace_write": True,
        "approved_workspace_promotion": True,
        "source_repository_write": False,
        "shell_execution": False,
        "direct_llama_proxy": False,
        "mcp_broker_foundation": True,
        "mcp_tool_execution": False,
    },
    "limits": {
        "request_body_max_bytes": 65536,
        "run_output_limit_bytes": 65536,
        "run_diff_limit_bytes": 32768,
        "run_queue_limit": 4,
        "run_retain_limit": 20,
        "session_max_turns": 12,
        "session_context_max_chars": 6000,
    },
    "run_modes": {
        "all": ["ci-fix", "diagnose", "fix", "implement", "plan", "refactor", "release", "review", "security"],
        "read_only": ["diagnose", "plan", "release", "review", "security"],
        "work": ["ci-fix", "fix", "implement", "refactor"],
    },
    "companion": {
        "name": "lai-gateway",
        "distribution": "separate-project",
        "role": "private client adapter for PWA, Telegram, or private-network transports",
        "token_handling": "keep the LAI control bearer token server-side; never send it to clients",
    },
    "forbidden_capabilities": [
        "generic_remote_shell",
        "direct_source_checkout_write",
        "dependency_installation",
        "host_environment_override",
        "commit_push_merge_or_pull_request_authority",
        "tag_or_release_publication_authority",
        "browser_automation_or_javascript_execution",
        "direct_llama_cpp_exposure_to_remote_clients",
        "control_token_or_model_api_key_disclosure",
    ],
    "routes": [
        {"method": "GET", "path": "/v1/gateway-contract", "auth_required": True, "purpose": "discover this contract"},
        {"method": "GET", "path": "/v1/status", "auth_required": True, "purpose": "read status"},
        {"method": "GET", "path": "/v1/readiness", "auth_required": True, "purpose": "read readiness"},
        {"method": "GET", "path": "/v1/mcp/status", "auth_required": True, "purpose": "read MCP broker status without executing tools"},
        {"method": "GET", "path": "/v1/mcp/tools", "auth_required": True, "purpose": "list declared MCP servers/tools without execution"},
        {"method": "POST", "path": "/v1/mcp/policy-check", "auth_required": True, "purpose": "classify MCP broker operation without execution"},
        {"method": "GET", "path": "/v1/runs?limit=N", "auth_required": True, "purpose": "list runs"},
        {"method": "POST", "path": "/v1/runs", "auth_required": True, "purpose": "enqueue run"},
        {"method": "GET", "path": "/v1/runs/{control_run_id}", "auth_required": True, "purpose": "read run"},
        {"method": "GET", "path": "/v1/runs/{control_run_id}/events", "auth_required": True, "purpose": "read run events"},
        {"method": "POST", "path": "/v1/sessions", "auth_required": True, "purpose": "create session"},
        {"method": "GET", "path": "/v1/sessions?limit=N", "auth_required": True, "purpose": "list sessions"},
        {"method": "GET", "path": "/v1/sessions/{session_id}", "auth_required": True, "purpose": "read session"},
        {"method": "DELETE", "path": "/v1/sessions/{session_id}", "auth_required": True, "purpose": "delete session"},
        {"method": "POST", "path": "/v1/policy-check", "auth_required": True, "purpose": "classify"},
        {"method": "GET", "path": "/v1/local-chat/contract?client_version=1", "auth_required": True, "purpose": "negotiate local chat"},
        {"method": "GET", "path": "/v1/local-chat/workspaces?client_version=1", "auth_required": True, "purpose": "list local workspaces"},
        {"method": "POST", "path": "/v1/local-chat/runs", "auth_required": True, "purpose": "enqueue local chat run"},
    ],
}
